[alias]
build-x86_64  = "build --target x86_64-unknown-none --bin busyos -Z build-std=core,compiler_builtins,alloc -Z build-std-features=compiler-builtins-mem"

[target.x86_64-unknown-none]
rustflags = [
  "-C", "code-model=kernel",
  "-C", "force-frame-pointers=y",
  "-C", "force-unwind-tables=n",
  "-C", "no-redzone=y",
  "-C", "panic=abort",
  "-C", "relocation-model=pie",
  "-C", "debuginfo=2",
]
