[package]
name = "busyos"
version = "0.1.0"
authors = ["Maxmade <28571007+MaxMade@users.noreply.github.com>"]
edition = "2024"

[dependencies]
kernel_derive = { path = "src/kernel/derive" }
arch_generic_derive = { path = "src/arch/generic/derive" }
driver_macro = { path = "src/driver/macro" }
bitfield-struct = { version = "0.13.0", default-features = false }
embedded-graphics = { version = "0.8.2", default-features = false }

[dev-dependencies]
nix = { version = "0.31.3", features = ["mman"] }
busyos = { path = ".", features = ["unittest"] }

[features]
unittest = []
library = []
