//! Abstraction for the x86_64 *Interrupt Descriptor Table* (IDT).
//!
//! The IDT holds one 16-byte gate per vector, pointing it at the `entry.S`
//! stub generated for that vector. [`Idt::new`] builds the table from
//! [`INTERRUPT_ENTRIES`] — the addresses `entry.S` publishes — and
//! [`Idt::init`]/[`Idt::load`] mirror [`Gdt::init`](crate::arch::x86_64::gdt::Gdt::init)/
//! [`Gdt::load`](crate::arch::x86_64::gdt::Gdt::load): the table is built
//! once and shared, while every core points its own `IDTR` at it.

use core::arch::asm;

use bitfield_struct::bitfield;

use crate::{
    arch::{
        Exceptions,
        x86_64::gdt::{Ring, SegmentSelector},
    },
    kernel::{
        locking::{CanAcquire, LockId, PreviousToken, ThreadLevelID},
        ticketlock::{ThreadTicketlock, Ticketlock},
    },
};

/// A single x86_64 IDT gate descriptor (16 bytes / 128 bits).
///
/// Describes one interrupt/trap gate: the handler address (split across
/// three fields), the code segment it runs under, the IST stack (if any),
/// its type, and the minimum privilege level required to invoke it via
/// software interrupt.
#[bitfield(u128)]
pub struct IdtEntry {
    /// Offset bits [15:0] — low 16 bits of the handler's address.
    #[bits(16)]
    pub offset_low: u16,

    /// Code segment selector in the GDT that the handler runs under.
    ///
    /// Must reference a valid 64-bit code segment descriptor. The CPL
    /// encoded in the selector's low 2 bits is not used for privilege
    /// checks here — see [`dpl`](IdtEntry::dpl) instead.
    #[bits(16)]
    pub selector: u16,

    /// Interrupt Stack Table index (bits [2:0] of byte 4).
    ///
    /// `0` means "do not switch stacks" (use the current stack, or the
    /// privilege-level stack from the TSS on a privilege change).
    /// `1`–`7` selects one of the seven IST stack pointers in the TSS,
    /// unconditionally switching to that stack on entry — used for
    /// handlers that must run on a known-good stack regardless of the
    /// interrupted context (e.g. double fault, NMI, machine check).
    #[bits(3)]
    pub ist: u8,

    /// Reserved. Must be zero.
    #[bits(5)]
    __: u8,

    /// Gate type (bits [11:8]).
    ///
    /// `0xE` = 64-bit interrupt gate (clears IF on entry).
    /// `0xF` = 64-bit trap gate (leaves IF unchanged on entry).
    /// Other encodings are invalid in long mode.
    #[bits(4)]
    pub gate_type: u8,

    /// Reserved (must be 0). Historically the "storage segment" bit,
    /// which must be 0 to mark this as a system descriptor.
    #[bits(1)]
    __: u8,

    /// Descriptor Privilege Level (bits [14:13]).
    ///
    /// The minimum CPL required to invoke this gate via a software
    /// interrupt (`int n`). Hardware-raised interrupts and exceptions
    /// ignore this check. Set to `3` to allow user-mode `int` instructions
    /// to reach the handler (e.g. a syscall gate); `0` otherwise.
    #[bits(2)]
    pub dpl: u8,

    /// Present bit (bit 15). Must be `1` for the CPU to consider this a
    /// valid gate; an entry with `present = false` raises `#GP` if invoked.
    #[bits(1)]
    pub present: bool,

    /// Offset bits [31:16] — middle 16 bits of the handler's address.
    #[bits(16)]
    pub offset_mid: u16,

    /// Offset bits [63:32] — high 32 bits of the handler's address.
    #[bits(32)]
    pub offset_high: u32,

    /// Reserved. Must be zero.
    #[bits(32)]
    __: u32,
}

impl IdtEntry {
    /// Gate type value for a 64-bit interrupt gate (clears IF on entry).
    const GATE_TYPE_INTERRUPT: u8 = 0xE;
}

unsafe extern "C" {
    /// Array of entry-point addresses generated by `entry.S`, one per vector.
    static INTERRUPT_ENTRIES: [u64; 256];
}

#[repr(C, align(16))]
pub struct Idt([IdtEntry; 256]);

impl Idt {
    /// Builds a table pointing every vector at its `entry.S` stub.
    ///
    /// Reads [`INTERRUPT_ENTRIES`], which only holds meaningful addresses
    /// once the kernel image is linked and loaded — so this cannot be a
    /// `const fn` run at compile time, unlike [`SegmentSelector`]'s table.
    pub const fn new() -> Self {
        let entry = IdtEntry::new()
            .with_selector(SegmentSelector::KERNEL_CODE.into_bits())
            .with_ist(0)
            .with_gate_type(IdtEntry::GATE_TYPE_INTERRUPT)
            .with_dpl(Ring::Zero as _)
            .with_present(true);

        Self([entry; 256])
    }

    /// Builds the kernel's table and publishes it as [`IDT`], for
    /// [`load`](Idt::load) to install on each core.
    ///
    /// # Safety
    ///
    /// This must run exactly once, on the core that boots, and before any
    /// core calls [`load`](Idt::load).
    ///
    /// # Token
    ///
    /// The `token` is consumed and returned.
    pub unsafe fn init<Token>(token: Token) -> Token
    where
        Token: CanAcquire<<ThreadLevelID as LockId>::Level> + PreviousToken,
    {
        let (mut guard, token) = IDT.acquire(token);
        for (i, slot) in guard.0.iter_mut().enumerate() {
            // SAFETY: `i` is in `0..256`, the length `INTERRUPT_ENTRIES` was
            // generated with.
            let handler = unsafe { INTERRUPT_ENTRIES[i] };

            *slot = slot
                .with_offset_low(handler as u16)
                .with_offset_mid((handler >> 16) as u16)
                .with_offset_high((handler >> 32) as u32);
        }

        // Enable `int3` (breakpoint) in user space.
        guard.0[Exceptions::Breakpoint as usize].set_dpl(Ring::Three as _);

        // Enable `int $0x80` (system call) in user space.
        guard.0[0x80].set_dpl(Ring::Three as _);

        guard.release(token)
    }

    /// Points this core's `IDTR` at the table [`init`](Idt::init) built.
    ///
    /// Every core runs this for itself: `lidt` is a per-core register, while
    /// the table behind it is shared.
    ///
    /// # Safety
    ///
    /// [`init`](Idt::init) must have run, and its table must still be the one
    /// [`IDT`] holds: this reads the static as an initialised `Idt`, which a
    /// zeroed one is not.
    ///
    /// # Token
    ///
    /// The `token` is consumed and returned.
    pub unsafe fn load<Token>(token: Token) -> Token
    where
        Token: CanAcquire<<ThreadLevelID as LockId>::Level> + PreviousToken,
    {
        let (guard, token) = IDT.acquire(token);

        // SAFETY: the caller guarantees that `init` has published a table.
        unsafe {
            let idtr = Idtr {
                limit: (size_of::<Idt>() - 1) as u16,
                base: guard.0.as_ptr() as u64,
            };

            asm!(
                "lidt [{idtr}]",
                idtr = in(reg) &idtr,
                options(nostack, preserves_flags),
            );
        }

        guard.release(token)
    }
}

/// The ten bytes `lidt` reads: where the table starts and how far it reaches.
#[repr(C, packed)]
struct Idtr {
    /// The offset of the last byte of the table, i.e. its size less one.
    limit: u16,

    /// The address the table starts at.
    base: u64,
}

pub static IDT: ThreadTicketlock<Idt> = ThreadTicketlock::new(Ticketlock::new(), Idt::new());
