[package]
name = "busyos-bootloader"
version = "0.1.0"
authors = ["Maxmade <28571007+MaxMade@users.noreply.github.com>"]
edition = "2024"

[dependencies]
elf = { version = "0.8.0", default-features = false }
busyos = { path = "../kernel", features = ["library"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
uefi = { version = "0.37.0", default-features = false, features = ["alloc", "global_allocator", "panic_handler"] }

[build-dependencies]

[features]
